/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2017-07-31 04:20:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class BandstructureChart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
      out.write("<title>Bandstructure</title>\n");
      out.write("<script src=\"https://cdn.plot.ly/plotly-latest.min.js\"></script>\n");
      out.write("\n");
      out.write("<style type=\"text/css\">\n");
      out.write("\n");
      out.write("\n");
      out.write(".modal .modal-body {\n");
      out.write("    max-height: 800px;\n");
      out.write("    overflow-y: auto;\n");
      out.write("}\n");
      out.write(".modal {\n");
      out.write("  text-align: center;\n");
      out.write("}\n");
      out.write("\n");
      out.write("@media screen and (min-width: 768px) {\n");
      out.write("  .modal:before {\n");
      out.write("    content: \" \";\n");
      out.write("    display: inline-block;\n");
      out.write("    height: 100%;\n");
      out.write("    vertical-align: middle;\n");
      out.write("  }\n");
      out.write("}\n");
      out.write("\n");
      out.write(".modal-dialog {\n");
      out.write("  display: inline-block;\n");
      out.write("  text-align: center;\n");
      out.write("  vertical-align: middle;\n");
      out.write("}\n");
      out.write("#BandstructureTable td\n");
      out.write("{\n");
      out.write("\tpadding-top: 5px ;\n");
      out.write("\tpadding-left:10px; ;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("    <script type=\"text/javascript\">\n");
      out.write("    var currentCompoundId;\n");
      out.write("    $(document).ready(function(){\n");
      out.write("    \t\n");
      out.write("    \t$(\"#CompoundElements\").change(function() {\n");
      out.write("    \t\n");
      out.write("    \t\tSetOrbitalValue($(this).val());\n");
      out.write("\n");
      out.write("    \t});\n");
      out.write("    \t\n");
      out.write("    \t\n");
      out.write("    \t\n");
      out.write("    });\n");
      out.write("    \n");
      out.write("    function SetOrbitalValue(orbitalValue)\n");
      out.write("    {\n");
      out.write("    \tvar orbitals = orbitalValue.replace(/^[\\s,]+|[\\s,]+$/g, '').split(',');\n");
      out.write("\t\t\n");
      out.write("    \t\n");
      out.write("\t\t $(\"#Orbitals\").html(''); \n");
      out.write("\t        $(\"#Orbitals\").append($(\"<option></option>\").val(\"None\").html(\"None\"));\n");
      out.write("\t\t  \t \n");
      out.write("\t\t $.each(orbitals, function (key, value) {\n");
      out.write("\t  \t         $(\"#Orbitals\").append($(\"<option></option>\").val(value).html(value));\n");
      out.write("\t  \t       });\n");
      out.write("    \t\n");
      out.write("    }\n");
      out.write("      function drawChart(bands,orbitalWeight) {  \n");
      out.write("    \t//  $(\"#Bands\").append($(\"<option></option>\").val('All').html('All'));\n");
      out.write("     \t\n");
      out.write("     \t  \n");
      out.write("     \t       drawBandChart(bands,orbitalWeight);\n");
      out.write("     \t  \n");
      out.write("          }\n");
      out.write("      \n");
      out.write("      \t  function drawBandChart(bands,orbitalWeight)\n");
      out.write("      \t  {\n");
      out.write("      \t\t\n");
      out.write("       \t  \n");
      out.write("      \t  BandChart = document.getElementById('BandChart');\n");
      out.write("      \t  Plotly.purge(BandChart);\n");
      out.write("  \t\t\n");
      out.write("      \t  var data =[];\n");
      out.write("      \t  var dx=[];\n");
      out.write("      \t  var w=[];\n");
      out.write("    \t  for(var i=0;i<bands[0].Energy.split(\", \").length;i++)\n");
      out.write("    \t  {       \t  dx.push(i);\n");
      out.write("    \t  \t\t\t  w.push(0);\n");
      out.write("    \t  }\n");
      out.write("    \t  for(var l=0;l<bands.length;l++)\n");
      out.write("      \t\t{\n");
      out.write("      \t\t  \n");
      out.write("      \t\t  var yval= bands[l].Energy.split(\", \");\n");
      out.write("      \t\t  var orbitalWeightVal=[];\n");
      out.write("      \t\t  if(orbitalWeight.length>0)\n");
      out.write("      \t\t  \torbitalWeightVal =orbitalWeight[l].split(\", \");\n");
      out.write("      \t\t  data.push({x:dx,\n");
      out.write("     \t\t\t  y:yval,\n");
      out.write("     \t\t\t  type: 'scatter',                    // set the chart type\n");
      out.write("    \t\t      mode: 'lines',   \n");
      out.write("    \t\t      line: {                             // set the width of the line.\n");
      out.write("    \t\t         width: 1\n");
      out.write("    \t\t      },\n");
      out.write("    \t\t      \n");
      out.write("    \t\t      error_y: {\n");
      out.write("    \t\t        array: orbitalWeightVal.length==0?w:orbitalWeightVal.map(function(x){return x/2;}),\n");
      out.write("    \t\t        thickness: 0.5,                   // set the thickness of the error bars\n");
      out.write("    \t\t        width: 0\n");
      out.write("    \t\t      }\n");
      out.write("     \t\t  \n");
      out.write("     \t\t  \n");
      out.write("     \t\t  });\n");
      out.write("     \t  \n");
      out.write("      \t\t}\n");
      out.write("      \t  \n");
      out.write("      \t\n");
      out.write("      \t var layout = {\n");
      out.write("       \t\t\t  title: 'Bandstructure ' ,\n");
      out.write("       \t\t\t \n");
      out.write("       \t\t\t\n");
      out.write("       \t\t\t  \n");
      out.write("       \t\t\t};\n");
      out.write("      \t  Plotly.plot( BandChart,data, layout );\n");
      out.write("      \t  }\n");
      out.write("      \t  \n");
      out.write("      \n");
      out.write("      \t\n");
      out.write("      \t  \n");
      out.write("      \t  \n");
      out.write("      \tfunction GetBandstructures(compoundid)\n");
      out.write("      \t{\n");
      out.write("      \t\tif(compoundid)\n");
      out.write("      \t\t{\n");
      out.write("      \t\t\tif(!currentCompoundId)\n");
      out.write("      \t\t\t\tcurrentCompoundId = compoundid;\n");
      out.write("      \t\t\telse if(currentCompoundId!=compoundid)\n");
      out.write("      \t\t\t{\n");
      out.write("      \t\t\t\tcurrentCompoundId = compoundid;\n");
      out.write("          \t\t\t\n");
      out.write("      \t\t\t\t$(\"#CompoundElements\").html('');\n");
      out.write("      \t\t\t\t$(\"#CompoundElements\").append($(\"<option></option>\").val(\"None\").html(\"None\"));\n");
      out.write("  \t\t\t  \t    \t\n");
      out.write("      \t\t\t\t$(\"#Orbitals\").html(''); \n");
      out.write("      \t\t        $(\"#Orbitals\").append($(\"<option></option>\").val(\"None\").html(\"None\"));\n");
      out.write("      \t\t\t  \t \n");
      out.write("      \t\t\t}\n");
      out.write("      \t\t\t\n");
      out.write("      \t\t}\n");
      out.write("      \t\t$('#dataStatus').show();\n");
      out.write("      \t\tvar eminBC= $(\"#EminBC\").val(),emaxBC=$(\"#EmaxBC\").val();\n");
      out.write("      \t\t$.get('BandStructureServlet', {\n");
      out.write("      \t\t\tEmin: eminBC.length==0?-10:eminBC,\n");
      out.write("      \t\t\tEmax: emaxBC.length==0?10:emaxBC,\n");
      out.write("      \t\t\telement:$(\"#CompoundElements option:selected\").text(),\n");
      out.write("      \t\t\torbital:$(\"#Orbitals\").val(),\n");
      out.write("      \t\t\tid:currentCompoundId \n");
      out.write("      \t\t\t }, function(data) { \n");
      out.write("      \t\t\t\t// $(\"#CompoundElements\").html(''); \n");
      out.write("      \t\t\t//\t    $(\"#CompoundElements\").append($(\"<option></option>\").val(\"None\").html(\"None\"));\n");
      out.write("      \t\t\t  \t    $('#dataStatus').hide();\n");
      out.write("      \t\t\t\t\tif(data.CompoundElementOrbitals.length>0)\n");
      out.write("      \t\t\t  \t    {\n");
      out.write("      \t\t\t  \t    \t$(\"#CompoundElements\").html('');\n");
      out.write("      \t\t\t  \t    \t\n");
      out.write("      \t\t\t  \t    \t\n");
      out.write("      \t\t\t  \t    \tSetOrbitalValue(data.CompoundElementOrbitals[0].Orbital);\n");
      out.write("      \t\t\t  \t    \t$.each(data.CompoundElementOrbitals, function (key, value) {\n");
      out.write("      \t\t\t  \t     \t   $(\"#CompoundElements\").append($(\"<option></option>\").val(value.Orbital).html(value.Element));\n");
      out.write("      \t\t\t  \t       });\n");
      out.write("      \t\t\t  \t    \t\n");
      out.write("      \t\t\t  \t    }\n");
      out.write("      \t\t     \t  drawChart(data.Bands,data.OrbitalWeight);\n");
      out.write("      \t\t     \t  \n");
      out.write("\n");
      out.write("      \t\t});      \t\t\n");
      out.write("      \t}\n");
      out.write("     \n");
      out.write("  \t\n");
      out.write("    </script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div  id=\"BandViewer\"  class=\"modal fade bs-example-modal-lg\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myLargeModalLabel\" style=\"width:100%\">\n");
      out.write("    <div class=\"modal-dialog modal-lg\">\n");
      out.write("     \n");
      out.write("      <!-- Modal content-->\n");
      out.write("      \n");
      out.write("       \n");
      out.write("      <div class=\"modal-content\">\n");
      out.write("        <div class=\"modal-header\">\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\n");
      out.write("          <h4 class=\"modal-title\" id=\"CompoundFormulaName\"></h4>\n");
      out.write("          \n");
      out.write("        </div>\n");
      out.write("        <div class=\"modal-body\">\n");
      out.write("    <div style=\"text-align: center;\">\n");
      out.write("    <table id=\"BandstructureTable\" >\n");
      out.write("    <tr>\n");
      out.write("\t    <td>\n");
      out.write("\t    \t<label>Emin:</label>\n");
      out.write("\t    </td>\n");
      out.write("\t    <td>\n");
      out.write("\t    \t<label>Emax:</label>\n");
      out.write("\t    </td>\n");
      out.write("\t    <td>\n");
      out.write("\t     <label  class=\"control-label \">Element </label>\n");
      out.write("    \t</td>\n");
      out.write("    \t<td>\n");
      out.write("    \t \n");
      out.write("\t\t<label  class=\"control-label \">Orbital</label>\n");
      out.write("    \t</td>\n");
      out.write("    \t<td>\n");
      out.write("    \t</td> \n");
      out.write("    </tr>\n");
      out.write("    <tr>\n");
      out.write("    <td>\n");
      out.write("   \t\t<input id=\"EminBC\" style=\"width:100px;\"  class=\"form-control\"  value=\"-10\">\n");
      out.write("\t</td>\n");
      out.write("\n");
      out.write("\t<td>\n");
      out.write("\t<input id=\"EmaxBC\" style=\"width:100px;\"  class=\"form-control\"  value=\"10\">\n");
      out.write("\t</td>\n");
      out.write("\t<td>\n");
      out.write("\t <select style=\"width: 100px; \" class=\"form-control\"   id=\"CompoundElements\">\n");
      out.write("\t\t\t\t\t<option value=\"None\">None</option>\t\t\n");
      out.write("\t\t</select>\n");
      out.write("\t</td>\n");
      out.write("\t<td>\n");
      out.write("\t <select style=\"width: 150px; \" class=\"form-control\"   id=\"Orbitals\">\n");
      out.write("\t\t\t<option value=\"None\">None</option>\n");
      out.write("\t\t</select>\n");
      out.write("\t</td>\n");
      out.write("\t<td>\n");
      out.write("\t<button style=\"width:100px;\" class=\"btn btn-secondary\" onclick=\"GetBandstructures()\">Get </button>\n");
      out.write("\t\t\n");
      out.write("\t</td>\n");
      out.write("\t<td >\n");
      out.write("\t<span id=\"dataStatus\" style=\"display: none;\"> Getting Data...</span>\n");
      out.write("\t</td>\n");
      out.write("\t</tr>\n");
      out.write("\t</table>\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("   <div id=\"BandChart\" style=\"width: 900px; height: 500px\"></div>\n");
      out.write("   \n");
      out.write("   \n");
      out.write("\n");
      out.write("<div id=\"ViewerContent\"  style=\"display: none;\"> <img src=\"\" id=\"imagepreview\" style=\"padding: 5px; width: 800px; height: 600px;\" ></div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"modal-footer\">\n");
      out.write("          <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      \n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("  \n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
