/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2016-06-30 17:18:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Compound_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Compound </title>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js\"></script>\r\n");
      out.write("<!-- Latest compiled and minified JavaScript -->\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js\" integrity=\"sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"js/jquery.tmpl.js\" type=\"text/javascript\"></script>   \r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t$(\"#NoResultText\").hide();\r\n");
      out.write("\t $(\"#CompoundTable\").hide();\r\n");
      out.write("\t \r\n");
      out.write("\t\t$('#elementName').text('");
      out.print(request.getParameter("ElementName"));
      out.write("');\r\n");
      out.write("\t\r\n");
      out.write("\t\tvar sg ='");
      out.print(request.getParameter("SpaceGroup"));
      out.write("';\r\n");
      out.write("\t$.get('CompoundServlet', {\r\n");
      out.write("\t\t AtomicNo : ");
      out.print(request.getParameter("AtomicNo"));
      out.write(",\r\n");
      out.write("\t\t AE: '");
      out.print(request.getParameter("AE"));
      out.write("',\r\n");
      out.write("\t\t IsShowAll:");
      out.print(request.getParameter("IsShowAll"));
      out.write(",\r\n");
      out.write("\t\t SpaceGroup :sg.length==0? 0:sg ,\r\n");
      out.write("\t\t CrystalSystem : '");
      out.print(request.getParameter("CrystalSystem"));
      out.write("', \r\n");
      out.write("\t\t }, function(compoundList) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t $(\"#NoResultText\").hide();\r\n");
      out.write("\t\t\t $(\"#CompoundTable\").hide();\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t if(compoundList.length==0)\r\n");
      out.write("\t\t\t {\r\n");
      out.write("\t\t\t\t $(\"#NoResultText\").show();\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t }\r\n");
      out.write("\t\t\t else\r\n");
      out.write("\t\t\t\t $(\"#CompoundTable\").show();\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t $(\"#NoResultText\").hide();\r\n");
      out.write("\t\t\t\t$(\"#CompoundContent\").html('');\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#CompoundListTemplate\").tmpl(compoundList).appendTo(\"#CompoundContent\");\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("function ViewCIF(codId)\r\n");
      out.write("{\r\n");
      out.write("\t\r\n");
      out.write("\t$.get('SingleCompoundServlet', {\r\n");
      out.write("\t\t CODId : codId \r\n");
      out.write("\t\t }, function(compound) {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar s = compound.Cif.replace(/(?:\\r\\n|\\r|\\n)/g, '<br />');\r\n");
      out.write("\t\t\t$('#CompoundFormula').text(compound.Formula);\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t$('#CifModal').modal();\t\r\n");
      out.write("\t\t\t$('#content').html(s);\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function DownloadCIF(codId)\r\n");
      out.write("{\r\n");
      out.write("\twindow.location = 'CIFServlet?CODId='+codId;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function GoToSingleCompound(codId)\r\n");
      out.write("{\r\n");
      out.write("\tlocation.href =  \"\\SingleCompound.jsp?CODId=\"+codId;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script id=\"CompoundListTemplate\"  type=\"text/x-jquery-tmpl\">\r\n");
      out.write("<tr>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<td><a style=\"cursor:pointer;\" onclick=\"GoToSingleCompound({{html CodID}})\"> {{html Formula }}</a></td>\r\n");
      out.write("\t<td>{{html SpaceGroup}}</td>\r\n");
      out.write("\t<td>{{html CrystalSystem}}</td>\r\n");
      out.write("\t  <td>{{html SpaceGroupName}}</td>\r\n");
      out.write("<td><a style=\"cursor: pointer;\" onclick=\"ViewCIF({{html CodID}});\">View</a> | <a style=\"cursor: pointer;\"  onclick=\"DownloadCIF({{html CodID}})\">Download</a>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</tr>\r\n");
      out.write("</script>\t\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled and minified CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css\" integrity=\"sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<!-- Optional theme -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css\" integrity=\"sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r\" crossorigin=\"anonymous\">\r\n");
      out.write("<script>\r\n");
      out.write("function goBack() {\r\n");
      out.write("    window.history.back();\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".main{\r\n");
      out.write("margin-top:-40px;\r\n");
      out.write("}\r\n");
      out.write("td,th{\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write(".modal .modal-body {\r\n");
      out.write("    max-height: 420px;\r\n");
      out.write("    overflow-y: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "leftSidebar.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"main\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"page-header\">\r\n");
      out.write("\t<h1><span id='elementName'></span> </h1>\r\n");
      out.write("</div>\r\n");
      out.write("<div style=\"float:right;\"><button class=\"btn btn-secondary\" onclick=\"goBack()\">Go Back</button></div>\r\n");
      out.write("<div style=\"clear:both;\"></div>\r\n");
      out.write("\r\n");
      out.write("\t<table id=\"CompoundTable\" class=\"table table-striped\">\r\n");
      out.write("\t    <thead>\r\n");
      out.write("\t      <tr>\r\n");
      out.write("\t        \r\n");
      out.write("\t        \r\n");
      out.write("\t \r\n");
      out.write("\t<th>Formula</th>\r\n");
      out.write("\t<th>Space Group</th>\r\n");
      out.write("\t<th>Crystal System</th>\r\n");
      out.write("\t  <th>Space Group Name</th>\r\n");
      out.write("\t  <th>CIF</th>\r\n");
      out.write("\r\n");
      out.write("\t      </tr>\r\n");
      out.write("\t    </thead>\r\n");
      out.write("\t    <tbody id=\"CompoundContent\">\r\n");
      out.write("\t    \r\n");
      out.write("\t    </tbody>\r\n");
      out.write("\t    </table>\r\n");
      out.write("\t    \r\n");
      out.write("\t    \r\n");
      out.write("\t         <div id=\"NoResultText\" >\r\n");
      out.write("\t    No Result Matched\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div  id=\"CifModal\"  class=\"modal fade bs-example-modal-lg\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myLargeModalLabel\">\r\n");
      out.write("    <div class=\"modal-dialog modal-lg\">\r\n");
      out.write("     \r\n");
      out.write("      <!-- Modal content-->\r\n");
      out.write("      \r\n");
      out.write("       \r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <div class=\"modal-header\">\r\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("          <h4 class=\"modal-title\" id=\"CompoundFormula\"></h4>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-body\">\r\n");
      out.write("       \r\n");
      out.write("<div id=\"content\" ></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-footer\">\r\n");
      out.write("          <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t \r\n");
      out.write("\t    \r\n");
      out.write("\t    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
