/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2016-11-29 20:34:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class leftSidebar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("    body,html{\r\n");
      out.write("\t\theight: 100%;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t/* remove outer padding */\r\n");
      out.write("\t.main .row{\r\n");
      out.write("\t\tpadding: 0px;\r\n");
      out.write("\t\tmargin: 0px;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t/*Remove rounded coners*/\r\n");
      out.write("\r\n");
      out.write("\tnav.sidebar.navbar {\r\n");
      out.write("\t\tborder-radius: 0px;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tnav.sidebar, .main{\r\n");
      out.write("\t\t-webkit-transition: margin 200ms ease-out;\r\n");
      out.write("\t    -moz-transition: margin 200ms ease-out;\r\n");
      out.write("\t    -o-transition: margin 200ms ease-out;\r\n");
      out.write("\t    transition: margin 200ms ease-out;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t/* Add gap to nav and right windows.*/\r\n");
      out.write("\t.main{\r\n");
      out.write("\t\tpadding: 10px 10px 0 10px;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t/* .....NavBar: Icon only with coloring/layout.....*/\r\n");
      out.write("\r\n");
      out.write("\t/*small/medium side display*/\r\n");
      out.write("\t@media (min-width: 768px) {\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t/*Allow main to be next to Nav*/\r\n");
      out.write("\t\t.main{\r\n");
      out.write("\t\t\tposition: absolute;\r\n");
      out.write("\t\t\twidth: calc(100% - 40px); /*keeps 100% minus nav size*/\r\n");
      out.write("\t\t\tmargin-left: 40px;\r\n");
      out.write("\t\t\tfloat: right;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t/*lets nav bar to be showed on mouseover*/\r\n");
      out.write("\t\tnav.sidebar:hover + .main{\r\n");
      out.write("\t\t\tmargin-left: 200px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t/*Center Brand*/\r\n");
      out.write("\t\tnav.sidebar.navbar.sidebar>.container .navbar-brand, .navbar>.container-fluid .navbar-brand {\r\n");
      out.write("\t\t\tmargin-left: 0px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t/*Center Brand*/\r\n");
      out.write("\t\tnav.sidebar .navbar-brand, nav.sidebar .navbar-header{\r\n");
      out.write("\t\t\ttext-align: center;\r\n");
      out.write("\t\t\twidth: 100%;\r\n");
      out.write("\t\t\tmargin-left: 0px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t/*Center Icons*/\r\n");
      out.write("\t\tnav.sidebar a{\r\n");
      out.write("\t\t\tpadding-right: 13px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t/*adds border top to first nav box */\r\n");
      out.write("\t\tnav.sidebar .navbar-nav > li:first-child{\r\n");
      out.write("\t\t\tborder-top: 1px #e5e5e5 solid;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t/*adds border to bottom nav boxes*/\r\n");
      out.write("\t\tnav.sidebar .navbar-nav > li{\r\n");
      out.write("\t\t\tborder-bottom: 1px #e5e5e5 solid;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t/* Colors/style dropdown box*/\r\n");
      out.write("\t\tnav.sidebar .navbar-nav .open .dropdown-menu {\r\n");
      out.write("\t\t\tposition: static;\r\n");
      out.write("\t\t\tfloat: none;\r\n");
      out.write("\t\t\twidth: auto;\r\n");
      out.write("\t\t\tmargin-top: 0;\r\n");
      out.write("\t\t\tbackground-color: transparent;\r\n");
      out.write("\t\t\tborder: 0;\r\n");
      out.write("\t\t\t-webkit-box-shadow: none;\r\n");
      out.write("\t\t\tbox-shadow: none;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t/*allows nav box to use 100% width*/\r\n");
      out.write("\t\tnav.sidebar .navbar-collapse, nav.sidebar .container-fluid{\r\n");
      out.write("\t\t\tpadding: 0 0px 0 0px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t/*colors dropdown box text */\r\n");
      out.write("\t\t.navbar-inverse .navbar-nav .open .dropdown-menu>li>a {\r\n");
      out.write("\t\t\tcolor: #777;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t/*gives sidebar width/height*/\r\n");
      out.write("\t\tnav.sidebar{\r\n");
      out.write("\t\t\twidth: 200px;\r\n");
      out.write("\t\t\theight: 100%;\r\n");
      out.write("\t\t\tmargin-left: -160px;\r\n");
      out.write("\t\t\tfloat: left;\r\n");
      out.write("\t\t\tz-index: 8000;\r\n");
      out.write("\t\t\tmargin-bottom: 0px;\r\n");
      out.write("\t\t\tposition: absolute;\r\n");
      out.write("\t\t\ttop:120px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t/*give sidebar 100% width;*/\r\n");
      out.write("\t\tnav.sidebar li {\r\n");
      out.write("\t\t\twidth: 100%;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t/* Move nav to full on mouse over*/\r\n");
      out.write("\t\tnav.sidebar:hover{\r\n");
      out.write("\t\t\tmargin-left: 0px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t/*for hiden things when navbar hidden*/\r\n");
      out.write("\t\t.forAnimate{\r\n");
      out.write("\t\t\topacity: 0;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t/* .....NavBar: Fully showing nav bar..... */\r\n");
      out.write("\r\n");
      out.write("\t@media (min-width: 1330px) {\r\n");
      out.write("\r\n");
      out.write("\t\t/*Allow main to be next to Nav*/\r\n");
      out.write("\t\t.main{\r\n");
      out.write("\t\t\twidth: calc(100% - 200px); /*keeps 100% minus nav size*/\r\n");
      out.write("\t\t\tmargin-left: 200px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t/*Show all nav*/\r\n");
      out.write("\t\tnav.sidebar{\r\n");
      out.write("\t\t\tmargin-left: 0px;\r\n");
      out.write("\t\t\tfloat: left;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t/*Show hidden items on nav*/\r\n");
      out.write("\t\tnav.sidebar .forAnimate{\r\n");
      out.write("\t\t\topacity: 1;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t#navigation{\r\n");
      out.write("        position: fixed;\r\n");
      out.write("    \t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\tnav.sidebar .navbar-nav .open .dropdown-menu>li>a:hover, nav.sidebar .navbar-nav .open .dropdown-menu>li>a:focus {\r\n");
      out.write("\t\tcolor: #CCC;\r\n");
      out.write("\t\tbackground-color: transparent;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tnav:hover .forAnimate{\r\n");
      out.write("\t\topacity: 1;\r\n");
      out.write("\t}\r\n");
      out.write("\tsection{\r\n");
      out.write("\t\tpadding-left: 15px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.navbar{\r\n");
      out.write("\t\tmargin-bottom: 0px;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"\">\r\n");
      out.write("function htmlbodyHeightUpdate(){\r\n");
      out.write("\tvar height3 = $( window ).height()\r\n");
      out.write("\tvar height1 = $('.nav').height()+50\r\n");
      out.write("\theight2 = $('.main').height()\r\n");
      out.write("\tif(height2 > height3){\r\n");
      out.write("\t\t$('html').height(Math.max(height1,height3,height2)+10);\r\n");
      out.write("\t\t$('body').height(Math.max(height1,height3,height2)+10);\r\n");
      out.write("\t}\r\n");
      out.write("\telse\r\n");
      out.write("\t{\r\n");
      out.write("\t\t$('html').height(Math.max(height1,height3,height2));\r\n");
      out.write("\t\t$('body').height(Math.max(height1,height3,height2));\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("$(document).ready(function () {\r\n");
      out.write("\thtmlbodyHeightUpdate()\r\n");
      out.write("\t$( window ).resize(function() {\r\n");
      out.write("\t\thtmlbodyHeightUpdate()\r\n");
      out.write("\t});\r\n");
      out.write("\t$( window ).scroll(function() {\r\n");
      out.write("\t\theight2 = $('.main').height()\r\n");
      out.write("\t\t\thtmlbodyHeightUpdate()\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<header style=\"height:120px;\" class=\"navbar navbar-bright  navbar-inverse\" role=\"banner\">\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <div class=\"navbar-header\">\r\n");
      out.write("      <button class=\"navbar-toggle\" type=\"button\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">\r\n");
      out.write("        <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("        <span class=\"icon-bar\"></span>\r\n");
      out.write("      </button>\r\n");
      out.write("       <a style=\"margin-top:-20px; margin-left:-70px; \" class=\"navbar-brand\" href=\"#\">\r\n");
      out.write("                    <img style=\"height:120px;width: 120px;\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/logo/f-orbital_logo.png\" alt=\"\">\r\n");
      out.write("                </a>\r\n");
      out.write("      <a style=\"font-size: 30px;\" href=\"/\" class=\"navbar-brand\">f-Electron Database</a>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div style=\"float: right; padding-top: 20px;\">\r\n");
      out.write("    <span >\r\n");
      out.write("\t<a style=\"padding-left: 10px;\"  class=\"pull-right\" href=\"\">\r\n");
      out.write("\t<img style=\"height:60px;width: 60px;\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/logo/upsala.png\" alt=\"The University of New Mexico\">\r\n");
      out.write("\t</a>\r\n");
      out.write("\t</span>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <span >\r\n");
      out.write("\t<a style=\"padding-left: 10px;\"  class=\"pull-right\" href=\"\">\r\n");
      out.write("\t<img style=\"height:60px;width: 160px;\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/logo/UNM.png\" alt=\"The University of New Mexico\">\r\n");
      out.write("\t</a>\r\n");
      out.write("\t</span>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <span>\r\n");
      out.write("\t<a  style=\"padding-right: 10px; padding-left: 10px;\" class=\"pull-right\" >\r\n");
      out.write("\t<img style=\"height:60px;width: 120px;\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/logo/logo_nordita.jpg\" >\r\n");
      out.write("\t</a>\r\n");
      out.write("\t</span>\r\n");
      out.write("\t\r\n");
      out.write("    \r\n");
      out.write("            <span>\r\n");
      out.write("\r\n");
      out.write("<a style=\"background: white; padding-right: 10px; \"  class=\"pull-right\" href=\"http://www.lanl.gov/\">\r\n");
      out.write("\t<img style=\"height:60px;width: 160px;\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/logo/LANL.png\" >\r\n");
      out.write("\t</a>\r\n");
      out.write("\t</span>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<span>\r\n");
      out.write("\t<a  style=\"padding-right: 10px;\" class=\"pull-right\" >\r\n");
      out.write("\t<img style=\"height:60px;width: 120px;\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/logo/IMS-logo-color.jpg\" >\r\n");
      out.write("\t</a>\r\n");
      out.write("\t</span>\r\n");
      out.write("    \r\n");
      out.write("</div>\r\n");
      out.write("    \r\n");
      out.write("  </div>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write(" <nav class=\"navbar navbar-inverse sidebar \" role=\"navigation\">\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("\t\t<!-- Brand and toggle get grouped for better mobile display -->\r\n");
      out.write("\t\t<!-- <div class=\"navbar-header\">\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#bs-sidebar-navbar-collapse-1\">\r\n");
      out.write("\t\t\t\t<span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t<span class=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"#\">Brand</a>\r\n");
      out.write("\t\t</div> -->\r\n");
      out.write("\t\t<!-- Collect the nav links, forms, and other content for toggling -->\r\n");
      out.write("\t\t<div class=\"collapse navbar-collapse\" id=\"bs-sidebar-navbar-collapse-1\">\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t<li class=\"active\"><a href=\"index.jsp\">Home<span style=\"font-size:16px;\" class=\"pull-right hidden-xs showopacity glyphicon glyphicon-home\"></span></a></li>\r\n");
      out.write("\t\t\t\t<li ><a href=\"People.jsp\">People<span style=\"font-size:16px;\" class=\"pull-right hidden-xs showopacity glyphicon glyphicon-user\"></span></a></li>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<li ><a href=\"Paper.jsp\">Paper<span style=\"font-size:16px;\" class=\"pull-right hidden-xs showopacity glyphicon glyphicon-envelope\"></span></a></li>\r\n");
      out.write("\t\t\t\t<li ><a href=\"About.jsp\">About<span style=\"font-size:16px;\" class=\"pull-right hidden-xs showopacity glyphicon glyphicon-exclamation-sign \"></span></a></li>\r\n");
      out.write("\t\t\t\t<li ><a href=\"Help.jsp\">Help<span style=\"font-size:16px;\" class=\"pull-right hidden-xs showopacity glyphicon glyphicon-cloud \"></span></a></li>\r\n");
      out.write("\t\t\t\t<li ><a href=\"DataViewer.jsp\">Data Viewer<span style=\"font-size:16px;\" class=\"pull-right hidden-xs showopacity glyphicon glyphicon-file\"></span></a></li>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t<!-- \t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Settings <span class=\"caret\"></span><span style=\"font-size:16px;\" class=\"pull-right hidden-xs showopacity glyphicon glyphicon-cog\"></span></a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu forAnimate\" role=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Action</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Another action</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Something else here</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"divider\"></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Separated link</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"divider\"></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">One more separated link</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>--> -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
