/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2017-04-10 21:14:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function Login()\r\n");
      out.write("{\r\n");
      out.write("\tvar userName = $(\"#namefield\").val();\r\n");
      out.write("    var pwd= $(\"#pwdfield\").val();\r\n");
      out.write("\tif((userName=='atowfiq'&&pwd=='fesdweb')||(userName=='abalatsky'&&pwd=='fesdweb'))\r\n");
      out.write("\t{\tlocation.href =  \"\\index.jsp\";\r\n");
      out.write("    \r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\telse \r\n");
      out.write("\t\talert(\"Invalid Username or Password\");\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>f-ESD</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tbackground: #eee !important;\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".wrapper {\t\r\n");
      out.write("\tmargin-top: 80px;\r\n");
      out.write("  margin-bottom: 80px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-signin {\r\n");
      out.write("  max-width: 380px;\r\n");
      out.write("  padding: 15px 35px 45px;\r\n");
      out.write("  margin: 0 auto;\r\n");
      out.write("  background-color: #fff;\r\n");
      out.write("  border: 1px solid rgba(0,0,0,0.1);  \r\n");
      out.write("\r\n");
      out.write("  .form-signin-heading,\r\n");
      out.write("\t.checkbox {\r\n");
      out.write("\t  margin-bottom: 30px;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.checkbox {\r\n");
      out.write("\t  font-weight: normal;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.form-control {\r\n");
      out.write("\t  position: relative;\r\n");
      out.write("\t  font-size: 16px;\r\n");
      out.write("\t  height: auto;\r\n");
      out.write("\t  padding: 10px;\r\n");
      out.write("\t\t@include box-sizing(border-box);\r\n");
      out.write("\r\n");
      out.write("\t\t&:focus {\r\n");
      out.write("\t\t  z-index: 2;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tinput[type=\"text\"] {\r\n");
      out.write("\t  margin-bottom: -1px;\r\n");
      out.write("\t  border-bottom-left-radius: 0;\r\n");
      out.write("\t  border-bottom-right-radius: 0;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tinput[type=\"password\"] {\r\n");
      out.write("\t  margin-bottom: 20px;\r\n");
      out.write("\t  border-top-left-radius: 0;\r\n");
      out.write("\t  border-top-right-radius: 0;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled and minified JavaScript -->\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js\" integrity=\"sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled and minified CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css\" integrity=\"sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<!-- Optional theme -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css\" integrity=\"sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r\" crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "topBar.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"main\" >\r\n");
      out.write("  <div class=\"wrapper\">\r\n");
      out.write("    <form class=\"form-signin\">       \r\n");
      out.write("      <h2 class=\"form-signin-heading\">Please login</h2>\r\n");
      out.write("      <input id=\"namefield\" type=\"text\" class=\"form-control\" name=\"username\" placeholder=\"Username\" required=\"\" autofocus=\"\" />\r\n");
      out.write("      \r\n");
      out.write("      <div style=\"height: 10px;\">\r\n");
      out.write("      </div>\r\n");
      out.write("      <input id=\"pwdfield\" type=\"password\" class=\"form-control\" name=\"password\" placeholder=\"Password\" required=\"\"/>      \r\n");
      out.write("      <label class=\"checkbox\">\r\n");
      out.write("       \r\n");
      out.write("      </label>\r\n");
      out.write("      <button class=\"btn btn-lg btn-primary btn-block\" type=\"button\" onclick=\"Login();\">Login</button>   \r\n");
      out.write("    </form>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
