/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2017-06-07 17:05:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class People_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>People</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js\"></script>\r\n");
      out.write("<!-- Latest compiled and minified JavaScript -->\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js\" integrity=\"sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled and minified CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css\" integrity=\"sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7\" crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/core-layout.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Optional theme -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css\" integrity=\"sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r\" crossorigin=\"anonymous\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".main{\r\n");
      out.write("margin-top:-40px;\r\n");
      out.write("}\r\n");
      out.write(".borderless td, .borderless tr {\r\n");
      out.write("    border: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "topBar.jsp", out, false);
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "leftSidebar.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"main\">\r\n");
      out.write("<div class=\"page-header\">\r\n");
      out.write("\t<h1><span >People</span> </h1>\r\n");
      out.write("</div>\r\n");
      out.write("<table class=\"borderless\" >\r\n");
      out.write("<tr>\r\n");
      out.write("<td>\r\n");
      out.write("\t<ul>\r\n");
      out.write("\t\t<li>\r\n");
      out.write("\t\t\t<a href=\"\">\r\n");
      out.write("\t\t\t\t<img style=\"width:200px;height: 160px;\" alt=\"thumbnail of Dr. Alexander V. Balatsky \" src=\"image/avb.jpg\">\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li>\r\n");
      out.write("\t\t<strong>Institute Director</strong>\r\n");
      out.write("\t\t</li><li>Dr. Alexander V. Balatsky </li>\r\n");
      out.write("\t\t<li>Institute for Materials Science</li>\r\n");
      out.write("\t\t<li>(505) 665-0077</li>\r\n");
      out.write("\t\t<li><a href=\"mailto:avb@lanl.gov\">\r\n");
      out.write("                          Email                        \r\n");
      out.write("   \t\t \t</a>\r\n");
      out.write("   \t\t </li>\r\n");
      out.write("\t\t </ul>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td> \r\n");
      out.write("\t\t\t <ul>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<a href=\"\">\r\n");
      out.write("\t\t\t\t\t<img style=\"width:180px;height: 160px;\"  src=\"image/ta.jpg\">\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t<strong>Staff Scientist, Theoretical Division</strong>\r\n");
      out.write("\t\t\t</li><li>Towfiq Ahmed</li>\r\n");
      out.write("\t\t\t<li> Los Alamos National Laboratory</li>\r\n");
      out.write("\t\t\t<li></li>\r\n");
      out.write("\t\t\t<li><a href=\"mailto:atowfiq@lanl.gov \">\r\n");
      out.write("\t                          Email                        \r\n");
      out.write("\t   \t\t \t</a>\r\n");
      out.write("\t   \t\t </li>\r\n");
      out.write("\t\t\t </ul>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t <ul>\r\n");
      out.write("\t\t<li>\r\n");
      out.write("\t\t\t<a href=\"\">\r\n");
      out.write("\t\t\t\t<img style=\"width:160px;height: 180px;\"   src=\"image/Mueen.jpg\">\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li>\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<strong>Assistant Professor</strong>\r\n");
      out.write("\t\t</li><li>\t\tAbdullah Mueen</li>\r\n");
      out.write("\t\t<li>Department of Computer Science</li>\r\n");
      out.write("\t\t<li>University of New Mexico</li>\r\n");
      out.write("\t\t<li><a href=\"mailto:mueen@cs.unm.edu \">\r\n");
      out.write("                          Email                        \r\n");
      out.write("   \t\t \t</a>\r\n");
      out.write("   \t\t </li>\r\n");
      out.write("\t\t </ul>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td> \r\n");
      out.write("\t\t\t <ul>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<a href=\"\">\r\n");
      out.write("\t\t\t\t\t<img style=\"width:150px;height: 160px;\"  src=\"image/jw.png\">\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t<strong>Staff Scientist, Theoretical Division</strong>\r\n");
      out.write("\t\t\t</li><li>John Wills</li>\r\n");
      out.write("\t\t\t<li> Los Alamos National Laboratory</li>\r\n");
      out.write("\t\t\t<li></li>\r\n");
      out.write("\t\t\t<li><a href=\"mailto:jxw@lanl.gov \">\r\n");
      out.write("\t                          Email                        \r\n");
      out.write("\t   \t\t \t</a>\r\n");
      out.write("\t   \t\t </li>\r\n");
      out.write("\t\t\t </ul>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("<td>\r\n");
      out.write("\t<ul>\r\n");
      out.write("\t\t<li>\r\n");
      out.write("\t\t\t<a href=\"\">\r\n");
      out.write("\t\t\t\t<img style=\"width:150px;height: 160px;\"  src=\"image/oe.jpg\">\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li>\r\n");
      out.write("\t\t<strong>Professor </strong>\r\n");
      out.write("\t\t</li><li>Olle Eriksson</li>\r\n");
      out.write("\t\t<li>Department of Physics and Astronomy</li>\r\n");
      out.write("\t\t<li>Materials Theory</li>\r\n");
      out.write("\t\t<li>Uppsala universitet</li>\r\n");
      out.write("\t\t<li><a href=\"mailto:olle.eriksson@physics.uu.se\">\r\n");
      out.write("                          Email                        \r\n");
      out.write("   \t\t \t</a>\r\n");
      out.write("   \t\t </li>\r\n");
      out.write("\t\t </ul>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<td>\r\n");
      out.write("\t<ul>\r\n");
      out.write("\t\t<li>\r\n");
      out.write("\t\t\t<a href=\"\">\r\n");
      out.write("\t\t\t\t<img style=\"width:160px;height: 160px;\"  src=\"image/hh.jpg\">\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t\t<li>\r\n");
      out.write("\t\t<strong>Researcher</strong>\r\n");
      out.write("\t\t</li><li>Heike Herper</li>\r\n");
      out.write("\t\t<li>Department of Physics and Astronomy</li>\r\n");
      out.write("\t\t<li>Materials Theory</li>\r\n");
      out.write("\t\t<li>Uppsala universitet</li>\r\n");
      out.write("\t\t<li><a href=\"mailto:heike.herper@physics.uu.se\">\r\n");
      out.write("                          Email                        \r\n");
      out.write("   \t\t \t</a>\r\n");
      out.write("   \t\t </li>\r\n");
      out.write("\t\t </ul>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td> \r\n");
      out.write("\t\t\t <ul>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<a href=\"\">\r\n");
      out.write("\t\t\t\t\t<img style=\"width:150px;height: 160px;\"  src=\"image/jz.jpg\">\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t<strong>Staff Scientist, Theoretical Division</strong>\r\n");
      out.write("\t\t\t</li><li>Jianxin Zhu</li>\r\n");
      out.write("\t\t\t<li>Los Alamos National Laboratory</li>\r\n");
      out.write("\t\t\t<li><a href=\"mailto:jxzhu@lanl.gov\">\r\n");
      out.write("\t                          Email                        \r\n");
      out.write("\t   \t\t \t</a>\r\n");
      out.write("\t   \t\t </li>\r\n");
      out.write("\t\t\t </ul>\r\n");
      out.write("\t\t</td>\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<td> \r\n");
      out.write("\t\t\t <ul>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<a href=\"\">\r\n");
      out.write("\t\t\t\t\t<img style=\"width:150px;height: 160px;\"  src=\"image/ak.jpg\">\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t<strong>Graduate Student (PhD)</strong>\r\n");
      out.write("\t\t\t</li><li>Adnan Ibne Khair</li>\r\n");
      out.write("\t\t\t<li> Department of Computer Science</li>\r\n");
      out.write("\t\t\t<li>University of New Mexico</li>\r\n");
      out.write("\t\t\t<li><a href=\"mailto:adnanibnekhair@unm.edu\">\r\n");
      out.write("\t                          Email                        \r\n");
      out.write("\t   \t\t \t</a>\r\n");
      out.write("\t   \t\t </li>\r\n");
      out.write("\t\t\t </ul>\r\n");
      out.write("\t\t</td>\t\r\n");
      out.write("\t\t</tr> \r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
