/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2017-04-12 09:08:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class rightSidebar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" <style >\r\n");
      out.write("   #right_panel {\r\n");
      out.write("    float: right;\r\n");
      out.write("    width: 180px;\r\n");
      out.write("    padding: 15px;\r\n");
      out.write("    padding-left: 0px;\r\n");
      out.write("    margin-top:100px;\r\n");
      out.write("    /* background-color: #E3F2FF; */\r\n");
      out.write("}\r\n");
      out.write(".linkSpace{\r\n");
      out.write("\tpadding:15px;\r\n");
      out.write("}\r\n");
      out.write(".imgcls{\r\n");
      out.write("\r\n");
      out.write("height:60px;\r\n");
      out.write("width: 120px;\r\n");
      out.write("}\r\n");
      out.write(" </style>\r\n");
      out.write(" <div style=\"clear: both;\"></div>\r\n");
      out.write("<div id=\"right_panel\" role=\"complementary\"> \r\n");
      out.write("<nav class=\"bs-docs-sidebar hidden-print hidden-sm hidden-xs affix\"> \r\n");
      out.write("<ul class=\"nav bs-docs-sidenav\"> \r\n");
      out.write("<ul class=\"nav\"> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<li class=\"linkSpace\">\r\n");
      out.write(" <span>\r\n");
      out.write("\r\n");
      out.write("\t<a href=\"http://www.lanl.gov/\" target=\"_blank\">\r\n");
      out.write("\t<img class=\"imgcls\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/logo/LANL.png\" >\r\n");
      out.write("\t</a>\r\n");
      out.write("\t</span> \r\n");
      out.write("</li> \r\n");
      out.write("<li class=\"linkSpace\">\r\n");
      out.write(" <span>\r\n");
      out.write("\r\n");
      out.write("\t<a href=\"http://www.lanl.gov/projects/national-security-education-center/institute-for-materials-science/\" target=\"_blank\">\r\n");
      out.write("\t<img class=\"imgcls\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/logo/IMS-logo-color.jpg\">\r\n");
      out.write("\t</a>\r\n");
      out.write("\t</span> \r\n");
      out.write("</li> \r\n");
      out.write("\r\n");
      out.write("<li class=\"linkSpace\">\r\n");
      out.write(" <span>\r\n");
      out.write("\r\n");
      out.write("\t<a href=\"https://www.nordita.org/\" target=\"_blank\">\r\n");
      out.write("\t<img class=\"imgcls\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/logo/norditax.png\">\r\n");
      out.write("\t</a>\r\n");
      out.write("\t</span> \r\n");
      out.write("</li> \r\n");
      out.write("\r\n");
      out.write("<li class=\"linkSpace\">\r\n");
      out.write(" <span>\r\n");
      out.write("\r\n");
      out.write("\t<a href=\"http://www.unm.edu/\" target=\"_blank\">\r\n");
      out.write("\t<img class=\"imgcls\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/logo/UNM.png\" >\r\n");
      out.write("\t</a>\r\n");
      out.write("\t</span> \r\n");
      out.write("</li> \r\n");
      out.write("\r\n");
      out.write("<li class=\"linkSpace\">\r\n");
      out.write(" <span>\r\n");
      out.write("\r\n");
      out.write("\t<a href=\"https://www.uu.se/en/\" target=\"_blank\">\r\n");
      out.write("\t<img class=\"imgcls\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/logo/upsala.png\" >\r\n");
      out.write("\t</a>\r\n");
      out.write("\t</span> \r\n");
      out.write("</li> \r\n");
      out.write(" </ul> \r\n");
      out.write("</ul>  </nav> </div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
