/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2017-07-31 08:48:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class SingleCompound_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
      out.write("<title>Compound </title>\n");
      out.write("\n");
      out.write(" <link rel=\"stylesheet\" href=\"css/ChemDoodleWeb.css\" type=\"text/css\">\n");
      out.write(" <script type=\"text/javascript\" src=\"js/ChemDoodleWeb.js\"></script>\n");
      out.write("\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js\"></script>\n");
      out.write("<!-- Latest compiled and minified JavaScript -->\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js\" integrity=\"sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"js/jquery.tmpl.js\" type=\"text/javascript\"></script> \n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("$(document).ready(function(){\n");
      out.write("\t$.get('SingleCompoundServlet', {\n");
      out.write("\t\tId: ");
      out.print(request.getParameter("Id"));
      out.write(" \n");
      out.write("\t\t }, function(compound) { \n");
      out.write("\t\t\t compound.BSExists=true;\n");
      out.write("\t\t\t Compound= compound;\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tLoadCif(compound.Cif); \n");
      out.write("\t\t//\t$(\"#cifViz\").html(new String(compound.Cif));\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t \n");
      out.write("\t\t\t $(\"#CompoundName\").text(compound.Formula);\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t \n");
      out.write("\t\t//\t $(\"#CompoundDetailsContent\").html('');\t\t\t\n");
      out.write("\t\t\t$(\"#CompoundDetailsTemplate\").tmpl(compound).appendTo(\"#CompoundDetailsContent\");\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("});\n");
      out.write("function LoadCif(cif)\n");
      out.write("{\n");
      out.write("\tvar MAZfile = cif;// you can change the 1s here to generate a supercell\n");
      out.write("\tvar maz = ChemDoodle.readCIF(MAZfile, 1, 1, 1);\n");
      out.write("\n");
      out.write("\t//setup component\n");
      out.write("\tvar crystalTransformer = new ChemDoodle.TransformCanvas3D('mol-canvas', 500, 500);\n");
      out.write("\t// set the atom/bond representation to 'Ball and Stick', although other representations are also useful for zeolites\n");
      out.write("\tcrystalTransformer.specs.set3DRepresentation('Ball and Stick');\n");
      out.write("\t// set the background color to black\n");
      out.write("\tcrystalTransformer.specs.backgroundColor = '#000000';\n");
      out.write("\t// declare an orthographic perspective to more easily see the zeolite pattern\n");
      out.write("\tcrystalTransformer.specs.projectionPerspective_3D = false;\n");
      out.write("\t// set the line widths for the unit cell to be 1.5 pixels\n");
      out.write("\tcrystalTransformer.specs.crystals_unitCellLineWidth = 1.5;\n");
      out.write("\t// set the unit cell line color to white\n");
      out.write("\tcrystalTransformer.specs.shapes_color = 'white';\n");
      out.write("\t// set the unit cell line width to 2\n");
      out.write("\tcrystalTransformer.specs.shapes_lineWidth = 2;\n");
      out.write("\tcrystalTransformer.specs.atoms_displayLabels_3D = true;\n");
      out.write("\n");
      out.write("\t \n");
      out.write("\n");
      out.write("\t  \n");
      out.write("\t  crystalTransformer.loadContent([maz.molecule], [maz.unitCell]);\n");
      out.write("\n");
      out.write("}\n");
      out.write("\n");
      out.write("function ViewCIF()\n");
      out.write("{\n");
      out.write("\tvar s = Compound.Cif.replace(/(?:\\r\\n|\\r|\\n)/g, '<br />');\n");
      out.write("\t$('#CompoundFormula').text(Compound.Formula);\t\n");
      out.write("\n");
      out.write("\t$('#CifModal').modal();\t\n");
      out.write("\t$('#content').html(s);\n");
      out.write("}\n");
      out.write("\n");
      out.write("function DownloadCIF()\n");
      out.write("{\n");
      out.write("\tvar downloadId;\t\n");
      out.write("\tif(Compound.Source ='cod')\n");
      out.write("\t\tdownloadId = Compound.CodID;\n");
      out.write("\telse\n");
      out.write("\t\tdownloadId =  Compound.ICSDID;\n");
      out.write("\twindow.location = 'CIFServlet?downloadId='+downloadId+\"&source=\"+Compound.Source;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("function ViewCompoundProperties(propType)\n");
      out.write("{\n");
      out.write("\t$('#CompoundFormulaName').text(Compound.Formula);\t\n");
      out.write("\n");
      out.write("\tvar src = '../static/View/';\n");
      out.write("\tvar srcId = '';\n");
      out.write("\tif (Compound.Source=='cod')\n");
      out.write("\t\tsrcId  = Compound.CodID;\n");
      out.write("\telse \n");
      out.write("\t\tsrcId  = Compound.ICSDID;\n");
      out.write("\tif(propType=='dos1'){\n");
      out.write("\t\tsrc = src + 'dos/'+Compound.Source+'/'+srcId+'100.png';\n");
      out.write("\t\t\t\n");
      out.write("\t}\n");
      out.write("\tif(propType=='dos2'){\t\t\n");
      out.write("\t\tsrc = src + 'dos/'+Compound.Source+'/'+srcId+'200.png';\n");
      out.write("\t}\n");
      out.write("\tif(propType=='dos3'){\n");
      out.write("\t\tsrc = src + 'dos/'+Compound.Source+'/'+srcId+'300.png';\n");
      out.write("\t\t\t\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\telse if(propType=='bs')\n");
      out.write("\t{\n");
      out.write("\t//\tsrc = src + 'bandstructure/'+Compound.Source+'/'+srcId+'.spaghetti_ps00.png';\n");
      out.write("\t\t\n");
      out.write("\t}\n");
      out.write("\telse if(propType=='fs')\n");
      out.write("\t{\n");
      out.write("\t\tsrc = '';\n");
      out.write("\t\t\n");
      out.write("\t}\n");
      out.write("\telse if(propType=='hf')\n");
      out.write("\t{\n");
      out.write("\t\tsrc = 'DataImage/hf.png';\n");
      out.write("\t\t\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t  $('#BandViewer').modal('show');\n");
      out.write("     //$('#Viewer').on('shown.bs.modal', function () {\n");
      out.write("    \t//GetBandstructures(Compound.Id);\n");
      out.write("    \t//alert('hello');\n");
      out.write("    \t//});\n");
      out.write("     GetBandstructures(Compound.Id);\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("function ViewDos(id)\n");
      out.write("{\n");
      out.write("\tGetDos(id);\t\n");
      out.write("}\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<script id=\"CompoundDetailsTemplate\"  type=\"text/x-jquery-tmpl\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<td>\n");
      out.write("<table class=\"table table-striped\">\n");
      out.write("<tr>\n");
      out.write("\t<td><strong>Source</strong></td>\t\n");
      out.write("\t<td>{{html Source}} - {{if Source == \"cod\"}}{{html CodID}}\n");
      out.write("{{/if}}\n");
      out.write("{{if Source == \"icsd\"}}{{html ICSDID}}\n");
      out.write("{{/if}}\n");
      out.write("</td>\n");
      out.write("</tr>\n");
      out.write("<tr>\n");
      out.write("\t<td><strong>Formula</strong></td>\t\n");
      out.write("\t<td>{{html Formula}}</td>\n");
      out.write("</tr>\n");
      out.write("<tr>\n");
      out.write("\t<td><strong>Space Group</strong></td>\n");
      out.write("\t\t<td>{{html SpaceGroup}}</td>\n");
      out.write("\n");
      out.write("</tr>\n");
      out.write("<tr>\n");
      out.write("\t<td><strong>Crystal System</strong></td>\n");
      out.write("\t\t<td>{{html CrystalSystem}}</td>\n");
      out.write("\n");
      out.write("</tr>\n");
      out.write("<tr>\n");
      out.write("\t<td><strong>Space Group Name</strong></td>\n");
      out.write("\t\t<td>{{html SpaceGroupName}}</td>\n");
      out.write("\n");
      out.write("</tr>\n");
      out.write("<tr>\n");
      out.write("\t<td><strong>Space Group Name Hall</strong></td>\n");
      out.write("\t\t<td>{{html SymmetrySpaceGroupNameHall}}</td>\n");
      out.write("\n");
      out.write("</tr>\n");
      out.write("<tr>\n");
      out.write("\t<td><strong>Cell Angle Alpha</strong></td>\n");
      out.write("\t\t<td>{{html CellAngleAlpha}}</td>\n");
      out.write("</tr>\n");
      out.write("<tr>\n");
      out.write("\t<td><strong>Cell Length A</strong></td>\n");
      out.write("\t\t<td>{{html CellLengthA}}</td>\n");
      out.write("</tr>\n");
      out.write("<tr>\n");
      out.write("\t<td><strong>Cell Length B</strong></td>\n");
      out.write("\t\t<td>{{html CellLengthB}}</td>\n");
      out.write("\n");
      out.write("</tr>\n");
      out.write("<tr>\n");
      out.write("\t<td><strong>Cell Length C</strong></td>\n");
      out.write("\t\t<td>{{html CellLengthC}}</td>\n");
      out.write("\n");
      out.write("</tr>\n");
      out.write("<tr>\n");
      out.write("\t<td><strong>Volume</strong></td>\n");
      out.write("\t\t<td>{{html CellVolume}}</td>\n");
      out.write("\n");
      out.write("</tr>\n");
      out.write("\n");
      out.write("{{if BSExists}}\n");
      out.write("<tr>\n");
      out.write("<td><strong>BandStructure</strong></td>\n");
      out.write("<td><button style=\"width:180px;\" class=\"btn btn-secondary\" onclick=\"ViewCompoundProperties('bs')\">BandStructure</button></td>\n");
      out.write("</tr>\n");
      out.write("{{/if}}\t \n");
      out.write("\n");
      out.write("{{if Dos1Exists}}\n");
      out.write("<tr>\n");
      out.write("<td><strong>Dos 1</strong></td>\n");
      out.write("<td><button style=\"width:180px;\" class=\"btn btn-secondary\" onclick=\"ViewCompoundProperties('dos1')\">Dos 1</button></td>\n");
      out.write("</tr>\n");
      out.write("{{/if}}\t \n");
      out.write("\n");
      out.write("{{if Dos2Exists}}\n");
      out.write("<tr>\n");
      out.write("<td><strong>Dos 2</strong></td>\n");
      out.write("<td><button style=\"width:180px;\" class=\"btn btn-secondary\" onclick=\"ViewCompoundProperties('dos2')\">Dos 2</button></td>\n");
      out.write("</tr>\n");
      out.write("{{/if}}\n");
      out.write("{{if Dos3Exists}}\n");
      out.write("<tr>\n");
      out.write("<td><strong>Dos 3</strong></td>\n");
      out.write("<td><button style=\"width:180px;\" class=\"btn btn-secondary\" onclick=\"ViewCompoundProperties('dos3')\">Dos 3</button></td>\n");
      out.write("</tr>\n");
      out.write("{{/if}}\t \n");
      out.write("\n");
      out.write("\n");
      out.write("<tr>\n");
      out.write("<td><strong>Dos</strong></td>\n");
      out.write("<td><button style=\"width:180px;\" class=\"btn btn-secondary\" onclick=\"ViewDos({{html Id}})\">Dos</button></td>\n");
      out.write("</tr>\n");
      out.write("\n");
      out.write("<tr>\n");
      out.write("<td><strong>CIF</strong></td>\n");
      out.write("<td>\n");
      out.write("<a style=\"cursor: pointer;\" onclick=\"ViewCIF();\">View</a> \n");
      out.write("</td>\n");
      out.write("</tr>\n");
      out.write("\n");
      out.write("</table>\n");
      out.write("</td>\n");
      out.write("\t\n");
      out.write("</script>\t\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- Latest compiled and minified CSS -->\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css\" integrity=\"sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7\" crossorigin=\"anonymous\">\n");
      out.write("\n");
      out.write("<!-- Optional theme -->\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css\" integrity=\"sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r\" crossorigin=\"anonymous\">\n");
      out.write("<style type=\"text/css\">\n");
      out.write(".main{\n");
      out.write("margin-top:-40px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write(".modal .modal-body {\n");
      out.write("    max-height: 800px;\n");
      out.write("    overflow-y: auto;\n");
      out.write("}\n");
      out.write(".modal {\n");
      out.write("  text-align: center;\n");
      out.write("}\n");
      out.write("\n");
      out.write("@media screen and (min-width: 768px) {\n");
      out.write("  .modal:before {\n");
      out.write("    content: \" \";\n");
      out.write("    display: inline-block;\n");
      out.write("    height: 100%;\n");
      out.write("    vertical-align: middle;\n");
      out.write("  }\n");
      out.write("}\n");
      out.write("\n");
      out.write(".modal-dialog {\n");
      out.write("  display: inline-block;\n");
      out.write("  text-align: center;\n");
      out.write("  vertical-align: middle;\n");
      out.write("}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("<script>\n");
      out.write("function goBack() {\n");
      out.write("    window.history.back();\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "topBar.jsp", out, false);
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "leftSidebar.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"main\">\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "BandstructureChart.jsp", out, false);
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "DosChart.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"page-header\">\n");
      out.write("\t<h1><span id='CompoundName'></span> </h1>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\t<div style=\"float:right;\"><button class=\"btn btn-secondary\" onclick=\"goBack()\">Go Back</button></div>\t    \n");
      out.write("\n");
      out.write("\t<div style=\"clear:both;\"></div>\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\t    <table style=\"padding-top: 10px;\" class=\"table\" >\n");
      out.write("\t    <tbody >\n");
      out.write("\t   \n");
      out.write("\t    <tr id=\"CompoundDetailsContent\"><td></td>\n");
      out.write("\t    <td >\n");
      out.write("\t    \t <figure> \n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<canvas id=\"mol-canvas\"></canvas>\n");
      out.write("  \t\t\t</figure>\n");
      out.write("\t    \n");
      out.write("\t    </td></tr>\n");
      out.write("\t    </tbody>\n");
      out.write("\t    </table>\n");
      out.write("\n");
      out.write("\n");
      out.write("<div  id=\"CifModal\"  class=\"modal fade bs-example-modal-lg\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myLargeModalLabel\">\n");
      out.write("    <div class=\"modal-dialog modal-lg\">\n");
      out.write("     \n");
      out.write("      <!-- Modal content-->\n");
      out.write("      \n");
      out.write("       \n");
      out.write("      <div class=\"modal-content\">\n");
      out.write("        <div class=\"modal-header\">\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\n");
      out.write("          <h4 class=\"modal-title\" id=\"CompoundFormula\"></h4>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"modal-body\">\n");
      out.write("       \n");
      out.write("<div id=\"content\" ></div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"modal-footer\">\n");
      out.write("          <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      \n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("  \t\n");
      out.write("\t\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
