/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2017-07-31 03:31:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class topBar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<style type=\"text/css\">\n");
      out.write("\n");
      out.write(".textPara{\n");
      out.write("\t color: #b52e17;\n");
      out.write("\t font-size: 18px;\n");
      out.write("\t font-weight: bold;\n");
      out.write("}\n");
      out.write("html *\n");
      out.write("{\n");
      out.write("   font-family: sans-serif ;\n");
      out.write("}\n");
      out.write("    body,html{\n");
      out.write("\t\theight: 100%;\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\t/* remove outer padding */\n");
      out.write("\t.main .row{\n");
      out.write("\t\tpadding: 0px;\n");
      out.write("\t\tmargin: 0px;\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\t/*Remove rounded coners*/\n");
      out.write("\n");
      out.write("\tnav.sidebar.navbar {\n");
      out.write("\t\tborder-radius: 0px;\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\tnav.sidebar, .main{\n");
      out.write("\t\t-webkit-transition: margin 200ms ease-out;\n");
      out.write("\t    -moz-transition: margin 200ms ease-out;\n");
      out.write("\t    -o-transition: margin 200ms ease-out;\n");
      out.write("\t    transition: margin 200ms ease-out;\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\t/* Add gap to nav and right windows.*/\n");
      out.write("\t.main{\n");
      out.write("\t\tpadding: 10px 10px 0 10px;\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\t/* .....NavBar: Icon only with coloring/layout.....*/\n");
      out.write("\n");
      out.write("\t/*small/medium side display*/\n");
      out.write("\t@media (min-width: 768px) {\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t/*Allow main to be next to Nav*/\n");
      out.write("\t\t.main{\n");
      out.write("\t\t\tposition: absolute;\n");
      out.write("\t\t\twidth: calc(100% - 40px); /*keeps 100% minus nav size*/\n");
      out.write("\t\t\tmargin-left: 40px;\n");
      out.write("\t\t\tfloat: right;\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\t/*lets nav bar to be showed on mouseover*/\n");
      out.write("\t\tnav.sidebar:hover + .main{\n");
      out.write("\t\t\tmargin-left: 200px;\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\t/*Center Brand*/\n");
      out.write("\t\tnav.sidebar.navbar.sidebar>.container .navbar-brand, .navbar>.container-fluid .navbar-brand {\n");
      out.write("\t\t\tmargin-left: 0px;\n");
      out.write("\t\t}\n");
      out.write("\t\t/*Center Brand*/\n");
      out.write("\t\tnav.sidebar .navbar-brand, nav.sidebar .navbar-header{\n");
      out.write("\t\t\ttext-align: center;\n");
      out.write("\t\t\twidth: 100%;\n");
      out.write("\t\t\tmargin-left: 0px;\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\t/*Center Icons*/\n");
      out.write("\t\tnav.sidebar a{\n");
      out.write("\t\t\tpadding-right: 13px;\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\t/*adds border top to first nav box */\n");
      out.write("\t\tnav.sidebar .navbar-nav > li:first-child{\n");
      out.write("\t\t\tborder-top: 1px #e5e5e5 solid;\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\t/*adds border to bottom nav boxes*/\n");
      out.write("\t\tnav.sidebar .navbar-nav > li{\n");
      out.write("\t\t\tborder-bottom: 1px #e5e5e5 solid;\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\t/* Colors/style dropdown box*/\n");
      out.write("\t\tnav.sidebar .navbar-nav .open .dropdown-menu {\n");
      out.write("\t\t\tposition: static;\n");
      out.write("\t\t\tfloat: none;\n");
      out.write("\t\t\twidth: auto;\n");
      out.write("\t\t\tmargin-top: 0;\n");
      out.write("\t\t\tbackground-color: transparent;\n");
      out.write("\t\t\tborder: 0;\n");
      out.write("\t\t\t-webkit-box-shadow: none;\n");
      out.write("\t\t\tbox-shadow: none;\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\t/*allows nav box to use 100% width*/\n");
      out.write("\t\tnav.sidebar .navbar-collapse, nav.sidebar .container-fluid{\n");
      out.write("\t\t\tpadding: 0 0px 0 0px;\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\t/*colors dropdown box text */\n");
      out.write("\t\t.navbar-inverse .navbar-nav .open .dropdown-menu>li>a {\n");
      out.write("\t\t\tcolor: #777;\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\t/*gives sidebar width/height*/\n");
      out.write("\t\tnav.sidebar{\n");
      out.write("\t\t\twidth: 200px;\n");
      out.write("\t\t\theight: 100%;\n");
      out.write("\t\t\tmargin-left: -160px;\n");
      out.write("\t\t\tfloat: left;\n");
      out.write("\t\t\tz-index: 8000;\n");
      out.write("\t\t\tmargin-bottom: 0px;\n");
      out.write("\t\t\tposition: absolute;\n");
      out.write("\t\t\ttop:120px;\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\t/*give sidebar 100% width;*/\n");
      out.write("\t\tnav.sidebar li {\n");
      out.write("\t\t\twidth: 100%;\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\t/* Move nav to full on mouse over*/\n");
      out.write("\t\tnav.sidebar:hover{\n");
      out.write("\t\t\tmargin-left: 0px;\n");
      out.write("\t\t}\n");
      out.write("\t\t/*for hiden things when navbar hidden*/\n");
      out.write("\t\t.forAnimate{\n");
      out.write("\t\t\topacity: 0;\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\t/* .....NavBar: Fully showing nav bar..... */\n");
      out.write("\t@media (min-width: 1100px)\n");
      out.write("\t{\n");
      out.write("\t\t.container{\n");
      out.write("\t\t\twidth:auto;\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t@media (min-width: 1200px)\n");
      out.write("\t{\n");
      out.write("\t\t.container{\n");
      out.write("\t\t\twidth:auto;\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("\t@media (min-width: 1330px) {\n");
      out.write("\n");
      out.write("\t\t/*Allow main to be next to Nav*/\n");
      out.write("\t\t.main{\n");
      out.write("\t\t\twidth: calc(100% - 200px); /*keeps 100% minus nav size*/\n");
      out.write("\t\t\tmargin-left: 200px;\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\t/*Show all nav*/\n");
      out.write("\t\tnav.sidebar{\n");
      out.write("\t\t\tmargin-left: 0px;\n");
      out.write("\t\t\tfloat: left;\n");
      out.write("\t\t}\n");
      out.write("\t\t/*Show hidden items on nav*/\n");
      out.write("\t\tnav.sidebar .forAnimate{\n");
      out.write("\t\t\topacity: 1;\n");
      out.write("\t\t}\n");
      out.write("\t\t#navigation{\n");
      out.write("        position: fixed;\n");
      out.write("    \t}\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\n");
      out.write("\tnav.sidebar .navbar-nav .open .dropdown-menu>li>a:hover, nav.sidebar .navbar-nav .open .dropdown-menu>li>a:focus {\n");
      out.write("\t\tcolor: #CCC;\n");
      out.write("\t\tbackground-color: transparent;\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\tnav:hover .forAnimate{\n");
      out.write("\t\topacity: 1;\n");
      out.write("\t}\n");
      out.write("\tsection{\n");
      out.write("\t\tpadding-left: 15px;\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t.navbar{\n");
      out.write("\t\tmargin-bottom: 0px;\n");
      out.write("\t}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("\n");
      out.write("<script src=\"\">\n");
      out.write("function htmlbodyHeightUpdate(){\n");
      out.write("\tvar height3 = $( window ).height()\n");
      out.write("\tvar height1 = $('.nav').height()+50\n");
      out.write("\theight2 = $('.main').height()\n");
      out.write("\tif(height2 > height3){\n");
      out.write("\t\t$('html').height(Math.max(height1,height3,height2)+10);\n");
      out.write("\t\t$('body').height(Math.max(height1,height3,height2)+10);\n");
      out.write("\t}\n");
      out.write("\telse\n");
      out.write("\t{\n");
      out.write("\t\t$('html').height(Math.max(height1,height3,height2));\n");
      out.write("\t\t$('body').height(Math.max(height1,height3,height2));\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("}\n");
      out.write("$(document).ready(function () {\n");
      out.write("\thtmlbodyHeightUpdate()\n");
      out.write("\t$( window ).resize(function() {\n");
      out.write("\t\thtmlbodyHeightUpdate()\n");
      out.write("\t});\n");
      out.write("\t$( window ).scroll(function() {\n");
      out.write("\t\theight2 = $('.main').height()\n");
      out.write("\t\t\thtmlbodyHeightUpdate()\n");
      out.write("\t});\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<header style=\"height:120px;\" class=\"navbar navbar-bright  navbar-inverse\" role=\"banner\">\n");
      out.write("  <div class=\"container\" >\n");
      out.write("  \n");
      out.write("     <div style=\"margin-left: 20px\" >\n");
      out.write("      <a style=\"font-size: 50px; \" href=\"/\" class=\"navbar-brand\">FESD</a>\n");
      out.write("       <a style=\"margin-top:-20px; \" class=\"navbar-brand\" href=\"#\">\n");
      out.write("                    <img style=\"height:120px;width: 120px;\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/logo/f-orbital_logo.png\" alt=\"\">\n");
      out.write("                </a>\n");
      out.write("    \n");
      out.write("      <a style=\"font-size: 30px;\" href=\"/\" class=\"navbar-brand\"><i>f</i>-Electron Structure Database</a>\n");
      out.write("     \n");
      out.write("      \n");
      out.write("      \n");
      out.write("    \n");
      out.write("      </div>\n");
      out.write("    <div class=\"navbar-header\">\n");
      out.write("      <button class=\"navbar-toggle\" type=\"button\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">\n");
      out.write("        <span class=\"sr-only\">Toggle navigation</span>\n");
      out.write("        <span class=\"icon-bar\"></span>\n");
      out.write("        <span class=\"icon-bar\"></span>\n");
      out.write("        <span class=\"icon-bar\"></span>\n");
      out.write("      </button>\n");
      out.write("   \n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("   \n");
      out.write("    \n");
      out.write("  </div>\n");
      out.write("</header>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
